package com.jissuetracker.webapp.models;
// Generated 9 Feb, 2016 6:00:21 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Attachments generated by hbm2java
 */
@Entity
@Table(name = "attachments", catalog = "IssueTracker")
public class Attachments implements java.io.Serializable {

	private Integer id;
	private Issues issues;
	private IssuesUpdates issuesUpdates;
	private String link;
	private Set<IssuesUpdates> issuesUpdateses = new HashSet<IssuesUpdates>(0);
	private Set<Issues> issueses = new HashSet<Issues>(0);

	public Attachments() {
	}

	public Attachments(Issues issues, IssuesUpdates issuesUpdates, String link, Set<IssuesUpdates> issuesUpdateses,
			Set<Issues> issueses) {
		this.issues = issues;
		this.issuesUpdates = issuesUpdates;
		this.link = link;
		this.issuesUpdateses = issuesUpdateses;
		this.issueses = issueses;
	}

	public Attachments(Integer id,Issues issues, IssuesUpdates issuesUpdates, String link, Set<IssuesUpdates> issuesUpdateses,
					   Set<Issues> issueses) {
		this.issues = issues;
		this.issuesUpdates = issuesUpdates;
		this.link = link;
		this.issuesUpdateses = issuesUpdateses;
		this.issueses = issueses;
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "issueId")
	public Issues getIssues() {
		return this.issues;
	}

	public void setIssues(Issues issues) {
		this.issues = issues;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "issueUpdatesId")
	public IssuesUpdates getIssuesUpdates() {
		return this.issuesUpdates;
	}

	public void setIssuesUpdates(IssuesUpdates issuesUpdates) {
		this.issuesUpdates = issuesUpdates;
	}

	@Column(name = "link", length = 300)
	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "attachments")
	public Set<IssuesUpdates> getIssuesUpdateses() {
		return this.issuesUpdateses;
	}

	public void setIssuesUpdateses(Set<IssuesUpdates> issuesUpdateses) {
		this.issuesUpdateses = issuesUpdateses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "attachments")
	public Set<Issues> getIssueses() {
		return this.issueses;
	}

	public void setIssueses(Set<Issues> issueses) {
		this.issueses = issueses;
	}

}
