package com.jissuetracker.webapp.models;
// Generated 16 Aug, 2016 4:09:04 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Attachments generated by hbm2java
 */
@Entity
@Table(name = "attachments", catalog = "IssueTracker")
public class Attachments extends SuperModelClass implements java.io.Serializable {

	private Integer id;
	private Issues issues;
	private IssuesUpdates issuesUpdates;
	private String link;
	private String originalName;

	public Attachments() {
	}

	public Attachments(Issues issues, IssuesUpdates issuesUpdates, String link, String originalName
					  ) {
		this.issues = issues;
		this.issuesUpdates = issuesUpdates;
		this.link = link;
		this.originalName = originalName;
	}



	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}



	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "issueId")
	public Issues getIssues() {
		return this.issues;
	}

	public void setIssues(Issues issues) {
		this.issues = issues;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "issueUpdatesId")
	public IssuesUpdates getIssuesUpdates() {
		return this.issuesUpdates;
	}

	public void setIssuesUpdates(IssuesUpdates issuesUpdates) {
		this.issuesUpdates = issuesUpdates;
	}

	@Column(name = "link", nullable = false, length = 500)
	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	@Column(name = "original_name", nullable = false, length = 200)
	public String getOriginalName() {
		return this.originalName;
	}

	public void setOriginalName(String originalName) {
		this.originalName = originalName;
	}


}
