package com.jissuetracker.webapp.models;
// Generated 1 Jul, 2016 12:54:00 PM by Hibernate Tools 4.0.0

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * EmailType generated by hbm2java
 */
@Entity
@Table(name = "email_type")
public class EmailType implements java.io.Serializable {

	private Integer id;
	private String type;

	public EmailType() {
	}

	public EmailType(String type) {
		this.type = type;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
