package com.jissuetracker.webapp.models;
// Generated 1 Jul, 2016 12:54:00 PM by Hibernate Tools 4.0.0

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Email generated by hbm2java
 */
@Entity
@Table(name = "email")
public class Email implements java.io.Serializable {

	private Integer id;
	private Integer type;
	private String content;
	private Date sendDateTime;
	private String sendTo;

	public Email() {
	}

	public Email(Integer type, String content, Date sendDateTime, String sendTo) {
		this.type = type;
		this.content = content;
		this.sendDateTime = sendDateTime;
		this.sendTo = sendTo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "content")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "send_date_time", length = 19)
	public Date getSendDateTime() {
		return this.sendDateTime;
	}

	public void setSendDateTime(Date sendDateTime) {
		this.sendDateTime = sendDateTime;
	}

	@Column(name = "send_to", length = 500)
	public String getSendTo() {
		return this.sendTo;
	}

	public void setSendTo(String sendTo) {
		this.sendTo = sendTo;
	}

}
